CREATE TABLE IF NOT EXISTS TEAMS_PROFILE(
TEAM CHAR(20),
FRANCHISE CHAR(50),
LEAGUE CHAR(10),
FROM_YEAR INT,
TO_YEAR INT,
YEARS INT,
GAMES INT,
WIN INT,
LOSS INT,
WIN_LOSS_RATIO REAL,
PLAYOFFS INT,
DIV_WINS INT,
CONF_WINS INT,
CHAMP_WINS INT
)

CREATE TABLE IF NOT EXISTS TEAMS_STATS(
TEAM CHAR(20),
FRANCHISE CHAR(50),
LEAGUE CHAR(10),
FROM_YEAR INT,
TO_YEAR INT,
YEARS INT,
GAMES INT,
WIN INT,
LOSS INT,
WIN_LOSS_RATIO REAL,
PLAYOFFS INT,
DIV_WINS INT,
CONF_WINS INT,
CHAMP_WINS INT
)

Name,Season,Lg,Team,W,L,W/L%,Finish,SRS,Pace,Rel_Pace,ORtg,Rel_ORtg,DRtg,Rel_DRtg,Playoffs,Coaches,Top WS


